# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];
  boot.supportedFilesystems = ["btrfs"];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/44fe5fc0-2226-4f76-9f22-3cd33e5d9166";
    fsType = "btrfs";
    options = ["subvol=root" "compress=zstd:1" "noatime"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/44fe5fc0-2226-4f76-9f22-3cd33e5d9166";
    fsType = "btrfs";
    options = ["subvol=nix" "compress=zstd:1" "noatime"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/44fe5fc0-2226-4f76-9f22-3cd33e5d9166";
    fsType = "btrfs";
    options = ["subvol=home" "compress=zstd:1" "noatime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CFC9-89B6";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/e83c2c24-e18b-429a-9f85-bee5687680e8";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
